In [2]:
import pandas as pd

# 2 Series

In [3]:
# 生成一个Series
ser_obj = pd.Series(range(10, 20)) #索引默认是从0-9
print(ser_obj) #打印输出会带有类型

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [4]:
print('-'*50)
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values)) #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype #数据类型

--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [8]:
print(ser_obj[0]) 
ser_obj[9] #
# 访问不存在的索引下标会报keyerror

10


np.int64(19)

In [9]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [10]:
#字典变为series，索引是字典的key，value是字典的value，感受非默认索引
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-'*50)
print(ser_obj2.index)
print('-'*50)
print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
Index([2001, 2005, 2003], dtype='int64')
--------------------------------------------------
17.8


array([17.8, 20.1, 16.5])

In [12]:
#有点鸡肋
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
print('-'*50)
print(ser_obj2.head())  #head默认显示前5行

temp
year1
temp
year1
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# 3 DataFrame

In [14]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0~2，0~3
print(t)
print('-'*50)


   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------


In [15]:
array = np.random.randn(5,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

[[ 0.46398585  0.76755425  0.02990732 -0.25474527]
 [-0.35344105  0.87238641 -1.42721468 -0.53000351]
 [-0.9634188  -1.09145672 -0.91487915  2.27344678]
 [-1.31131205 -1.56117963 -0.1279764  -0.44354856]
 [ 2.23519228 -1.06444168 -0.0685656   1.20256387]]
--------------------------------------------------
          0         1         2         3
0  0.463986  0.767554  0.029907 -0.254745
1 -0.353441  0.872386 -1.427215 -0.530004
2 -0.963419 -1.091457 -0.914879  2.273447
3 -1.311312 -1.561180 -0.127976 -0.443549
4  2.235192 -1.064442 -0.068566  1.202564


In [24]:
t.loc[0] #单独把某一行取出来,类型是series
#loc[] 是基于标签的索引器，0 是行标签（即行索引名）。返回行索引为 0 的那一行数据，类型为 Series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [26]:
# 列表套字典 变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [27]:
pd.Series(1, index=list(range(3,7)),dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [29]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)


   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [31]:
print('-'*50)
print(df_obj2.index) #行索引,重点
#不可改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
df_obj2.dtypes #每一列的数据类型，重点

--------------------------------------------------
Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')


A             int64
B    datetime64[us]
C           float32
D             int32
E               str
F               str
dtype: object

In [33]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6) #创建一个日期时间索引，生成6个时间点，默认频率freq='D'，即按天递增
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-'*50)
print(df.index)


                   A         B         C         D
2013-01-01 -0.235054  0.835961  0.404084 -0.505523
2013-01-02  0.861163 -0.947942  0.622383 -0.085799
2013-01-03 -1.598009  1.916929  1.923937  0.235377
2013-01-04  0.125866  0.179602 -0.911125  0.807354
2013-01-05 -0.661883  0.172041 -0.402199  1.443128
2013-01-06 -0.060792  1.921773 -0.115942 -0.743604
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')


In [34]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B'])
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[us]
--------------------------------------------------
<class 'pandas.Series'>


In [35]:
#增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [36]:
# 删除列
del(df_obj2['G'])
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
